name = "upstream"
main = "src/index.ts"
compatibility_date = "2026-09-10"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "upstream"
database_id = "3dff162c-3c60-4f80-8b9e-10f49e4956bd"
