-- build_tags / domain_tags: keyword tags read from a company's real description by
-- ingest/tags.py, as JSON arrays. What it builds (hardware, software, biological or chemical)
-- and where it is used (health, energy, ...). Keywords about the words, not a judgement about
-- the company; never read from a list's label. NULL: not computed yet; []: nothing matched.
--
-- Generated on 15 September 2026 from the live rows, so the filters work before the next run;
-- every run recomputes them. $0: no model was asked anything.
ALTER TABLE companies ADD COLUMN build_tags TEXT;
ALTER TABLE companies ADD COLUMN domain_tags TEXT;
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = '109-nano-composite-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = '2d-matx';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '[]' WHERE id = '30m-genomics';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'a3-remote-monitoring-technologies';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'aagamiseq-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'aagyavision';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'aakhash-advanced-materials';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'abee-research-labs';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["energy", "manufacturing & industry", "buildings & construction"]' WHERE id = 'abigh-art';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "energy", "mobility", "space & aerospace", "manufacturing & industry"]' WHERE id = 'abx3-pv';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'abyom-spacetech-and-defence';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'accelerd-sciences';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'acceleron-labs';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'accensible-solutions';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'acells-imprint';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'actorius-innovations-and-research';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'acuradyne-medical-systems';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'addauto-technology';
UPDATE companies SET build_tags = '["hardware", "software", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'adiuvo-diagnostics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'advanced-manufacturing-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'advanced-renewable-tandem-photovoltaics-india';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'advantech-mi-systems';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'aerodel-technology-innovations';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["space & aerospace"]' WHERE id = 'aerogravity';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'aerolith-technology';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'aerovity-advanced-system';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'affinity-automation-controls';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'agam-agritech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'agautomate';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace"]' WHERE id = 'agnikul-cosmos';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["defence & security", "manufacturing & industry"]' WHERE id = 'agnit-semiconductors';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'agniva-aerospace';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["water & environment"]' WHERE id = 'agregators-enterprises-efeed';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "buildings & construction"]' WHERE id = 'agri-joy';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'agrikhet-ecoharvest-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food"]' WHERE id = 'agrivista-ai';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food", "water & environment", "manufacturing & industry"]' WHERE id = 'agrotick';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'ahammune-biosolutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ai-ezer-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'ai-health-highway';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'ai-sense';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["agriculture & food"]' WHERE id = 'aibono-smart-farming';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'aicheng-innovation-and-research';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["water & environment"]' WHERE id = 'aishwarya-dasare';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'aiva-healthcare-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ajithaprodrug-india';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'akshaisarathi-health-care-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "water & environment", "buildings & construction"]' WHERE id = 'albatross-energetics';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["space & aerospace", "defence & security", "manufacturing & industry", "education"]' WHERE id = 'algobotix';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'algodelta-solutions';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "manufacturing & industry"]' WHERE id = 'algosurg-inc';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'alpha-feeder-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'altravia-global';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'amaterasu-lifesciences';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy", "water & environment", "buildings & construction"]' WHERE id = 'ambiator';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'amdus-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'ameliorate-biotech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'ameya-universe-system';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ammsemi';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'amsh-endeavours';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'amyscan-healthcare';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment"]' WHERE id = 'anagha-cleaners';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'analyticsplus-india';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'anatomech';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment", "manufacturing & industry", "buildings & construction"]' WHERE id = 'angirus';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'aniket-kenge';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'ankur-agarwal';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'annoviant-healthcare';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'anuna-nanotech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'anvi-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'appliedc6-technologies';
UPDATE companies SET build_tags = '["software", "biological or chemical"]', domain_tags = '["water & environment"]' WHERE id = 'apratima-biosolutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'aquaforge-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'aradhya-skytron';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["water & environment"]' WHERE id = 'arc-robotics';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["defence & security", "finance"]' WHERE id = 'arishti-cybertech';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food"]' WHERE id = 'arkashine-innovations';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'arkle-energy-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'arms-4-ai';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'arogriha';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'arunoday-innovations-and-research';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'asat-automation';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'ashva-wearable-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["space & aerospace"]' WHERE id = 'astrome-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["mobility", "space & aerospace"]' WHERE id = 'astrophel-aerospace';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ateon-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy"]' WHERE id = 'atlast-motogen';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "space & aerospace"]' WHERE id = 'atmospheric-flight-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'atre-healthtech';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'atreya-innovations';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'aubotz-labs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'auflows-cardiotech';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'augle-a-i';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'aur-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'aursys-dynamics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'autosegra-solution';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'avinya-neurotech';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["energy", "mobility", "space & aerospace"]' WHERE id = 'avkalan-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'avp-star';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'ayati-devices';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ayu-devices';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace"]' WHERE id = 'baas-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'backstage-dynamics';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'banofi-leather';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'bariflo-cybernetics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'barox-oxytec';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'battezy-energy';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy", "water & environment"]' WHERE id = 'baud-resources';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'bcd-analytics-hub';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace"]' WHERE id = 'bellatrix-aerospace';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'best-nanotech';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'bharati-robotic-systems-india';
UPDATE companies SET build_tags = '[]', domain_tags = '["health", "agriculture & food", "space & aerospace", "defence & security"]' WHERE id = 'bhoomicam';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace"]' WHERE id = 'bigdipper-exploration-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'bike-spa-international';
UPDATE companies SET build_tags = '[]', domain_tags = '["defence & security", "manufacturing & industry"]' WHERE id = 'binford-research-labs';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'bio-synth';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'biodimension-technology';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'bioinnovatiq-lifescience';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'biolockey-healthworks';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'biomarkiq-scientific-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'bionano-integra-healthcare-opc';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'bionic-hope';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'bioprime-agrisolutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'bioprobe-lab';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["water & environment"]' WHERE id = 'biovalriz';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["defence & security", "manufacturing & industry"]' WHERE id = 'bit-mapper-integration-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'bleetech-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'blue-heart-robotics';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["defence & security"]' WHERE id = 'blurgs-innovations';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["education"]' WHERE id = 'bodhiverse';
UPDATE companies SET build_tags = '["software", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'boltzmann-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy"]' WHERE id = 'bombay-bijlee';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'bonarep-materials';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'botloka';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'boviedge-research';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'bpc-bioproducts';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "mobility"]' WHERE id = 'brainbuds-healthcare';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'brainovative-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'brainwaves-neurorehab-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'bramhansh-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'bumblebee-instruments';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'buzzworthy-ventures';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'byas-biorefineries';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'bylin-medtech';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy", "defence & security"]' WHERE id = 'c-tech-labs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'caldor-health-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "water & environment", "manufacturing & industry"]' WHERE id = 'call-x-ringers';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "manufacturing & industry"]' WHERE id = 'caloreon-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'canary-biosensors';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "manufacturing & industry"]' WHERE id = 'cancrie';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy", "water & environment"]' WHERE id = 'carbsorb-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'careflex-health';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'caregenix-diagnotech';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["manufacturing & industry", "education"]' WHERE id = 'carimo-technologies';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'cellom-biologicals';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'cellsion-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'chaitanya-nanotechnology';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'chemgreen-innovations';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'cheminpharma-products';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'chimertech';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "energy", "water & environment"]' WHERE id = 'circular-ecotech';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'clairvoyance-mindware';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'clarity-bio-systems-india';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'club-first-robotics';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["finance"]' WHERE id = 'coin-mobile-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'collcraft-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'colmed-health-tech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'cology-biosciences';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'combat-robotics-india';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'consilium-ventures';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'constrobots-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'corr-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'craste';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'cre-aid-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'crisprbits';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'curelink';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'curexel-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'cvit-solution';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'cyclops-medtech';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'cygenica';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "manufacturing & industry"]' WHERE id = 'cygni-energy';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'cypherx';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'd-rube-labs-and-research';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'dartforge-autonomous-systems';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment"]' WHERE id = 'darukaa-esg-technology';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'darwin-digitech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'declutter-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'dee-dee-labs';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'deepaarogya';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'deepak-ghavari';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'delta-botanicals-and-research';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'delta-nanoventions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'denika-lab-tech-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'denovo-bioinnovations';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'densepower';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'desintox-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'devadros-automata';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'dfine-bio-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'dhanya-nanotech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'dharmayukta';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'dhenoo-tech-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'dhi-sathi-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'dhruv-electro';
UPDATE companies SET build_tags = '[]', domain_tags = '["health", "water & environment"]' WHERE id = 'diagopreutic';
UPDATE companies SET build_tags = '[]', domain_tags = '["space & aerospace"]' WHERE id = 'digantara-research-and-technologies';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'divisha-innovations';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'docsapp-phasorz-technologies';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'docswallet-tharakan-web-innovations';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'doto-health';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace", "education"]' WHERE id = 'drona-aviation';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'dronelab-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'dronesarthi';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'droplets-innovative-incinerators';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'drpashu-ai-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "space & aerospace", "defence & security", "manufacturing & industry"]' WHERE id = 'dtown-robotics';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["education"]' WHERE id = 'durjeya-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'duuet';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'dverse-technologies';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["water & environment"]' WHERE id = 'e3biocleantech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'earthtech-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'easescan-medtech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ecoet-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment", "manufacturing & industry", "buildings & construction"]' WHERE id = 'ecostrata-infra';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'edhaa-innovations';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'ednam-soultions';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'edsix-brain-lab';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["education"]' WHERE id = 'edutor-technologies-india';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'effecmed';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food"]' WHERE id = 'ekosight-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'elamani-tech';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["energy", "mobility"]' WHERE id = 'electica-energy';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'electrine-ingenum-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'electronlab';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'elemio-materials';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'elevenrobotics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility", "manufacturing & industry"]' WHERE id = 'elexo-energy';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'elmentoz-research';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'elvitron-technologies';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'embright-infotech';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["agriculture & food", "manufacturing & industry"]' WHERE id = 'emertech-innovations';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'emflux-motors';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'endimension-technology';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'energybae';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'enervanta-electronics';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'enlife';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'epocare';
UPDATE companies SET build_tags = '["hardware", "software", "biological or chemical"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'equine-biotech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'esres-tech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ethereal-exploration-guild';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "space & aerospace"]' WHERE id = 'etherx-ai';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food"]' WHERE id = 'euphotic-labs';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'exinovous-healthcare-technologies';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'exocan-healthcare-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'exovian-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'exquinz-life-sciences';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'exsure';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy"]' WHERE id = 'extra-watts-renewables';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace", "manufacturing & industry"]' WHERE id = 'fabheads-automation';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food"]' WHERE id = 'farmassistant';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "agriculture & food", "space & aerospace"]' WHERE id = 'farmicon-india';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'fastsense-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'feetwings';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility", "water & environment"]' WHERE id = 'felis-leo-widgets';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'femacare';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'fermentech-labs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'ferry-lifesciences';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "manufacturing & industry"]' WHERE id = 'feynman-energy';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["agriculture & food", "energy"]' WHERE id = 'fibsol-life-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'fins-and-tails-agritech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'flash-cryogenics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'flavinlabs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'flexmotion-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility", "water & environment"]' WHERE id = 'florafarad-energy';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'flourishing-panckosha';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'fluoresight-bioprobes';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["space & aerospace"]' WHERE id = 'flytbase';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'focalpreneur-technologies-services';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'fontierz';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'footryx-healthcare';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'forschmedx';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'freeman-robots';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'fubotics';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'fuma-labs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "space & aerospace"]' WHERE id = 'fuselage-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'galanto-innovations';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["water & environment"]' WHERE id = 'gamasusco';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'gaucello';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'gaze';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'gbact-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "water & environment"]' WHERE id = 'gd-environmental';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'genoscope';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'genrobotic-innovations';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["agriculture & food"]' WHERE id = 'genz-materials';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health", "mobility", "space & aerospace", "finance"]' WHERE id = 'geospekter-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'gigamind-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "space & aerospace"]' WHERE id = 'gigaton-research';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'gloport-photonix-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'glorious-enviro-and-space-soft-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'glovatrix';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'gnl-neuro-think-soft-solution';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'gohemp-agro-ventures';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'gpc-lifesciences';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["agriculture & food"]' WHERE id = 'green-collar-agritech-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'green-grahi-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy", "water & environment", "manufacturing & industry"]' WHERE id = 'green-trek-research-and-development';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'greenathon-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["health", "agriculture & food", "energy", "water & environment", "manufacturing & industry", "buildings & construction"]' WHERE id = 'greenjams-buildtech';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "energy", "water & environment", "manufacturing & industry"]' WHERE id = 'greenshift-energy';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'greyeast-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility"]' WHERE id = 'grinntech-motors-services';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'gritly-analytics';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy", "mobility"]' WHERE id = 'gudlyf-mobility';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'gurutva-systems';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health", "education"]' WHERE id = 'gut-buddy-healthcare-services';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'gwolts-transformers';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'gyrfalcon-intelliedge-solutions-india';
UPDATE companies SET build_tags = '["hardware", "software", "biological or chemical"]', domain_tags = '["health", "manufacturing & industry"]' WHERE id = 'gyroid-photonics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'gyrotronix-robots';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "manufacturing & industry"]' WHERE id = 'h2e-power-systems';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'hab-biomass';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'hama-iot';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health", "water & environment"]' WHERE id = 'hariharan-sekar';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'harmonix-research';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food"]' WHERE id = 'harvtech';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'haystack-analytics';
UPDATE companies SET build_tags = '[]', domain_tags = '["manufacturing & industry"]' WHERE id = 'hbs-lifesciences';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'heal-agnostic';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'healthseq-precision-medicine';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'hem-dimensions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "manufacturing & industry", "education"]' WHERE id = 'hmv-drives';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'holo-abdul-inventions';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'hornet-biologicals';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["water & environment", "manufacturing & industry"]' WHERE id = 'hrimtron-energy-systems';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'hughen-tech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "water & environment"]' WHERE id = 'hycosys';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy"]' WHERE id = 'hydrovert-energy';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'hyper-stealth-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "manufacturing & industry"]' WHERE id = 'hyperonic-engineering';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'hyperspawn';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'i-eon';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food"]' WHERE id = 'idam-agrobiotech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ignomagine';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'igrenenergi-services';
UPDATE companies SET build_tags = '["software", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'ikesia-biologics';
UPDATE companies SET build_tags = '[]', domain_tags = '["finance"]' WHERE id = 'ikuber-financial-services-imf';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'immunitasbio';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'immunitoai';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'immunoadoptive-cell-therapy';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'imran-hussain';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'imrobonix';
UPDATE companies SET build_tags = '[]', domain_tags = '["defence & security"]' WHERE id = 'imumbai-semiconductor';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'inav-agrp-mech';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'incartis-therapeutics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'indent-designs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "manufacturing & industry"]' WHERE id = 'indigenous-energy-storage-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'indius-mediproducts';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'indrarjun-ai-automation-and-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'indrobotix-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["space & aerospace", "defence & security", "manufacturing & industry"]' WHERE id = 'indrones-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'industron-technical-services';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "space & aerospace", "defence & security", "manufacturing & industry"]' WHERE id = 'infab-semiconductor';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment"]' WHERE id = 'infixen-energy';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["agriculture & food", "mobility", "manufacturing & industry"]' WHERE id = 'infyu-labs';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["education"]' WHERE id = 'ingenium-education';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'inger-therapeutics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'innaumation-medical-devices';
UPDATE companies SET build_tags = '[]', domain_tags = '["education"]' WHERE id = 'innolyf';
UPDATE companies SET build_tags = '[]', domain_tags = '["education"]' WHERE id = 'inopen-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'inovaugmet-research';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace"]' WHERE id = 'inspecity-space-laboratories';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'inte-elabs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'integri-robotics-and-automation';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'intellizon-energy';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'international-center-for-nano-devices';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'intignus-bio';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'intisen-technology';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'invention-labs-engineering-products';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment", "manufacturing & industry"]' WHERE id = 'invoviron-industries-trading';
UPDATE companies SET build_tags = '[]', domain_tags = '["health", "energy"]' WHERE id = 'ionbridge-tech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'iowit-technologies';
UPDATE companies SET build_tags = '["software", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'iqsoft-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'ira-medical-technology';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["water & environment"]' WHERE id = 'iris-ecotech';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'irov-eyerov-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ishitva-robotic-systems';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'ismo-bio-photonics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'ixar-robotic-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'jagaddhatri-data-analytics-and-engineering';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["water & environment"]' WHERE id = 'jalviks';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'jana-enterprises';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'jatayu-healthcare-technologies';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'jeevatva-biosciences';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'jnps-oxyjoy';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food"]' WHERE id = 'joyponic-farms';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'jsp-electronics-india';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food"]' WHERE id = 'jyosh-ai-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'kailash-cosmos-aerospace-systems';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'kaiza-health';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'kalki-robotics-opc';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'kamireddy-agro-foods';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace"]' WHERE id = 'kasvik-geospatial-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'kaundinya-automation';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'kavachrix';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["energy", "manufacturing & industry"]' WHERE id = 'kavirise-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'kbcols-sciences';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'kerax-a-subsidiary-of-keralink-international';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'keshava-elite-projects';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'khojiq-tech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'kidyfit-care';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'kissanconnect';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food"]' WHERE id = 'klonec-automation-systems';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'kore-additive-manufacturing-and-medical-reconstruction';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'kozhnosys';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'kreator-3d-printer-and-solutions';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'krishiboot-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "manufacturing & industry"]' WHERE id = 'kristelle-dental-implants';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food"]' WHERE id = 'kritsnam-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'krypton-automation';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'lamark-biotech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'lambdapoint-innovation';
UPDATE companies SET build_tags = '[]', domain_tags = '["education"]' WHERE id = 'languify';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'leads-genetics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'leofelis-instruments';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'lhp-nano-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["water & environment"]' WHERE id = 'life-and-limb';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'lifeseed-reproductive-healthcare';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'lifespark-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'lisha-awasthi';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'log9-materials-scientific';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'logicboots';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'logy-ai';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["space & aerospace"]' WHERE id = 'lumin-aerospace';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'm-defense-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'm-h-electronics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'mabgenex';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'macof-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'magheals';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'magnimous-info-tech';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'manastik-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'mani-aerospace';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'marche-healthcare';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'matolutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'matsolvion';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "water & environment", "manufacturing & industry"]' WHERE id = 'matterak-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'matterwave-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'mechanoweb';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food", "manufacturing & industry"]' WHERE id = 'mechbot';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'med-inno-tech';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'medblue-innovations';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'medfassst-healthcare';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'medprime-technologies';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'medrinz-bio';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'medtrion-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'meerkats-heatcrafters';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'meerkats-innovative-technotools';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'meerkats-nanotherm-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy"]' WHERE id = 'meine-electric-automotive';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'metal-rp';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'metalumina';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'microx-pratimesh-labs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'mimyk';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'module-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'mohit-velaskar';
UPDATE companies SET build_tags = '["software", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'moldoc-biotech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'mrobotics';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'mushloop';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'mydentist-ai';
UPDATE companies SET build_tags = '[]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'mylab-discovery-solutions';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'mynvax';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'nagesh-nayak';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nano-advantage';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'nano-connect-semicon';
UPDATE companies SET build_tags = '["hardware", "software", "biological or chemical"]', domain_tags = '["health", "defence & security", "manufacturing & industry"]' WHERE id = 'nanoai-technology';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health", "energy", "space & aerospace", "defence & security"]' WHERE id = 'nanoalpha-innovatics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanoapthi';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanoharvestx-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanokem-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanomika-solutionz';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanoqom-research-and-development';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanosapience';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'nanosniff-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanospin-technologies';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'nanotherapx-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanothink-spectrum-opc';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nanovistar';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment"]' WHERE id = 'naturewrks';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food"]' WHERE id = 'naturex-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "energy"]' WHERE id = 'nava-design-innovation';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'navstream-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'nayam-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy", "water & environment", "manufacturing & industry"]' WHERE id = 'ncf-green-energy';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'neer-shakti-systems';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'neevaram';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'neo-avishkars';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'neodrive-technologies';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'neomavericks-ai';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'neroex-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'neuaurelius';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'neuranics-lab';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'neuresko-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'neurostellar';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace", "defence & security"]' WHERE id = 'newspace-research-technologies';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'nex-fitzap';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nextgen-ems';
UPDATE companies SET build_tags = '[]', domain_tags = '["health", "manufacturing & industry"]' WHERE id = 'nidhi-pandey';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nilico-green-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nine-innovative-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nirvaan';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'njyme-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nkure-therapeutics';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "energy", "mobility", "water & environment"]' WHERE id = 'noble-exchange-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nocomat';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'norththerm-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nova-dynamix';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nubiogenx';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'numelo-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nutricape';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'nutrigenetics-life-science';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '[]' WHERE id = 'nuvelle-approche';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'nw-engineering';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'nxtq';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility", "manufacturing & industry"]' WHERE id = 'offgrid-energy-labs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'oko-icare-solutions';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health", "manufacturing & industry"]' WHERE id = 'omnibrx-biotechnologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'oneomics';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'onestop-wellness';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'open-medlabs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'openhorizon-labs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'optify-industrial-solution';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'orhin';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'origo-dynamics';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'orthocrafts-innovations';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["energy", "water & environment", "manufacturing & industry"]' WHERE id = 'ossus-biorenewables';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'ostic-pharma';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'oxobot-robotics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'pacify-medical-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["education"]' WHERE id = 'paleru-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'pankhtech-india';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'papyrus-diagnostics';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["agriculture & food"]' WHERE id = 'pasidi-panta';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'path-shodh-healthcare';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'pe-wala';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'pecsa-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'penguin-innovative-engineering';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "buildings & construction"]' WHERE id = 'perovskite-innovation';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'phonologies-india';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "water & environment"]' WHERE id = 'photom-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'picraft-technology';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'plabs-solutions';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'planys-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'plasmo-sense';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'plotnew-bio-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'polymeric-sensors';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'polyorbit';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'powai-labs-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility", "buildings & construction"]' WHERE id = 'powerzest-energy-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'pragmatech-healthcare';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'prana-xenotransplants';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'pratiti-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "energy", "mobility", "water & environment", "manufacturing & industry", "buildings & construction"]' WHERE id = 'prayas-greentech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'prayasta-3d';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'precisurg';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'priyanka-yasaslapu';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'pro-virtual-technology-automations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'probird';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'profprenuer-innovations';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["agriculture & food"]' WHERE id = 'proleri-technologies';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'promecens';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["education"]' WHERE id = 'prosical-language-technologies';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'protein-design';
UPDATE companies SET build_tags = '["software", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'proteomica-international';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'protobots';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'proxi-farma';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food"]' WHERE id = 'proximal-soilsens-technologies';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'qawach-bio';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'qualivon-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'quan2d-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'queliz-lifetech';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'quixotix-bioprinting';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'qunu-labs';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'ragavera-indic-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'rana-semiconductors';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'rar-makaraa-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "space & aerospace"]' WHERE id = 'raveneye-geospatial';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'raycura-medical-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["space & aerospace", "defence & security", "manufacturing & industry"]' WHERE id = 'rebhu-computing';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility", "space & aerospace"]' WHERE id = 'rechargion-energy';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'rejuvome-therapeutics';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'relsym-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "energy", "water & environment"]' WHERE id = 'renkube';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'renu-medtech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'reseapro-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment", "manufacturing & industry"]' WHERE id = 'revy-environmental-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'ripple-healthcare';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'rmb-engineers';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'roberon-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'robolife';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'robosquad-innovators';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'robotex';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'robotics-data';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'robotoai-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'robotutor-tech';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'roha-precision-systems-development';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'roha369-biotech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'rosa-technology';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'rounak-timble';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'rrs-projectx-cloud-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'rural-surgery-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'rygen-dynamics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility"]' WHERE id = 'rym-grenergy-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'rymo-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["education", "finance"]' WHERE id = 'safexpay';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'sakura-biotech';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health", "agriculture & food", "manufacturing & industry"]' WHERE id = 'sal-biosciences';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'samaritan-ai';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'samvedan-technology';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food"]' WHERE id = 'saraaga-agri-robo-tech';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'sarbit-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'sarvottam-ai';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "finance"]' WHERE id = 'satat-gram-services';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'satavic-innovations';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["agriculture & food"]' WHERE id = 'sattvaponics-solutions-proeon';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "manufacturing & industry"]' WHERE id = 'scilogic-applied-research';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'scitechesy-research-and-technology';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'sedemac-mechatronics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'sense-it-out-intelligent-solutions';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food"]' WHERE id = 'senseqube-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'sensivision-health-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "manufacturing & industry"]' WHERE id = 'serigen-mediproducts';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'serocode-biolabs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'sh-forhealth';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'shanmukha-innovations';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '[]' WHERE id = 'shantani-proteome-analytics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'shasunmed-lifesciences';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'shieldnex-aerospace-india';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'shivram-badhe';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'shodhsens-diagnostics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'shree-veerabhadreshwara-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'shrikant-nanomaterials-research';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["agriculture & food", "manufacturing & industry"]' WHERE id = 'shuvoneel-ras-system';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'siamaf-healthcare';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food"]' WHERE id = 'sickle-innovations';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'sicuremi-healthcare-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'silicocean';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'silifarm-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'skincurate-research';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'skiom';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "agriculture & food", "energy", "space & aerospace", "manufacturing & industry", "buildings & construction"]' WHERE id = 'skylark-drones';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'smart-walking-cane';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'soilo-agricultural-solutions';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "energy"]' WHERE id = 'solar-farms';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["water & environment", "manufacturing & industry"]' WHERE id = 'solinas-integrity';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "water & environment", "manufacturing & industry"]' WHERE id = 'sorting-swans-ecosocial';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'soulsense-innovations';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace", "defence & security"]' WHERE id = 'spacefields';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'spaceock-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'sparshmind-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'spectraabridge-analytics-centre';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'spenca-global-services';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'spotdot-bioinnovations';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'spotsense-healthcare-solutions';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["water & environment"]' WHERE id = 'sprih-labs';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["mobility", "space & aerospace", "manufacturing & industry"]' WHERE id = 'sristan-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food"]' WHERE id = 'ss-agriqulture-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ssky-aerospace-industries';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'stealthtech-research-labs';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food", "manufacturing & industry", "finance"]' WHERE id = 'stellapps-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'stemtech-medical-devices';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'strider-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'subtlebotic';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'sumaitra-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'sunqulp-tech';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'super-good-nano';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "water & environment"]' WHERE id = 'supernit-shinde';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'superq-technologies-india';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'suryudey-plastic-electronics';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["energy"]' WHERE id = 'sustain-co';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["water & environment"]' WHERE id = 'sustainol-solutions';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["space & aerospace", "manufacturing & industry", "buildings & construction"]' WHERE id = 'sustivonai-pvt-ltd-doing-business-as-sustivon';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food"]' WHERE id = 'svachal-automation';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'swiftwing-robotics';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'synersense';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'synova-advanced-surfaces';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'synthera-biomedicals';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "education"]' WHERE id = 'tactopus-learning-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'tatva-core';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'taurmed-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'tavisha-robotics';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["energy", "water & environment"]' WHERE id = 'taypro';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'tc-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'tealaa-innovations';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health", "manufacturing & industry"]' WHERE id = 'techinvention-lifecare';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'technext-lab';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '[]' WHERE id = 'tenxer-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'teralumen-solutions';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["agriculture & food", "space & aerospace", "water & environment", "finance"]' WHERE id = 'terrastack-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'tervis-medical-systems';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'tetrel-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'texabyte-opc';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["agriculture & food"]' WHERE id = 'tgp-bioplastics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'tharam-thiran-green-energy-flow';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'theranautilus';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy", "water & environment"]' WHERE id = 'thermopv-solar';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "space & aerospace"]' WHERE id = 'thrustworks-dynetics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health", "agriculture & food", "manufacturing & industry"]' WHERE id = 'tishyas-medical-device-development-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment", "manufacturing & industry"]' WHERE id = 'tracexero-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'trachealth-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'transfinity-spacetech';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'transformer-neural-scan-quest-ai';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'translead-medtech-private-limited-earlier-neuintegrals-medtech';
UPDATE companies SET build_tags = '["hardware", "software", "biological or chemical"]', domain_tags = '["health"]' WHERE id = 'transpact-enterprises';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["education"]' WHERE id = 'trestle-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment"]' WHERE id = 'tri-om';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'trident-laser';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["education"]' WHERE id = 'trilingo';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy"]' WHERE id = 'trinano-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'trinnovate-synergy-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'triraksha-robotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'trizlabz';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["space & aerospace", "defence & security", "manufacturing & industry"]' WHERE id = 'tsalla-aerospace';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'tvaster-genkalp';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health", "finance"]' WHERE id = 'uber-diagnostics';
UPDATE companies SET build_tags = '[]', domain_tags = '["energy"]' WHERE id = 'umagine-hydrogen';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'umarobotics';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'umarobotics-technology';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'unibose-engineering-india';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'unicas-biotech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'unino-healthcare';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "energy", "water & environment"]' WHERE id = 'uniurja';
UPDATE companies SET build_tags = '[]', domain_tags = '["water & environment", "manufacturing & industry"]' WHERE id = 'universallygreen-technology';
UPDATE companies SET build_tags = '["hardware", "biological or chemical"]', domain_tags = '[]' WHERE id = 'univigor-innovative';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'uoc-graphene-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ur-advanced-therapeutics';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "energy"]' WHERE id = 'urbanwind-technology';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["water & environment"]' WHERE id = 'urjanovac';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'utopic-tech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "mobility"]' WHERE id = 'uvera-mobility';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'valcories-industries';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'vasishth-genomics-research-lab';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food", "space & aerospace"]' WHERE id = 'vasundharaa-geo-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility"]' WHERE id = 'vaultionix-energy';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'vaxigen-international-research-centre';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health", "agriculture & food"]' WHERE id = 'vaxineer';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["manufacturing & industry"]' WHERE id = 'vctr-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'vegen-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'vendit-automation';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'vertical-farming-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'vetra';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'vexon-automation';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'vi-hab-solutions';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["water & environment"]' WHERE id = 'via-energicals';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '[]' WHERE id = 'vidcare-innovations';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'vidcare-technologies';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["health"]' WHERE id = 'vigorus-healthtech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'vigyanllm';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'virbhadra-implants';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["mobility", "water & environment", "manufacturing & industry"]' WHERE id = 'viridian-ingni-propulsion';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food", "water & environment"]' WHERE id = 'vision-earthcare';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'vitacrop-technologies';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["energy", "mobility"]' WHERE id = 'voltrez-tech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'voxelcore-advanced-technologies';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health"]' WHERE id = 'vytal-healthtech';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'vyuti-systems';
UPDATE companies SET build_tags = '["hardware", "software"]', domain_tags = '["agriculture & food", "energy", "space & aerospace", "defence & security", "water & environment"]' WHERE id = 'weathercast-solutions';
UPDATE companies SET build_tags = '["software"]', domain_tags = '[]' WHERE id = 'webaroo-technology-india';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'whistl-healthtech';
UPDATE companies SET build_tags = '["hardware"]', domain_tags = '["health"]' WHERE id = 'whiteowl-health-care';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'whiterabbit-ai-technologies';
UPDATE companies SET build_tags = '[]', domain_tags = '["agriculture & food"]' WHERE id = 'wingrow-agritech-innovations';
UPDATE companies SET build_tags = '["biological or chemical"]', domain_tags = '["health"]' WHERE id = 'wissenkraft-labs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'wonderlend-hubs';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'xact-diagnotek';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'xanvora';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'xpredict-automation-solutions';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ylectric-technology';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'yrr-edutech';
UPDATE companies SET build_tags = '["software"]', domain_tags = '["health", "energy", "defence & security", "manufacturing & industry"]' WHERE id = 'zenteiq-aitech-innovations';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'zentek-nanotech-india';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'zerocircle-alternatives';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'zeroearth';
UPDATE companies SET build_tags = '[]', domain_tags = '["health"]' WHERE id = 'zia-ventures';
UPDATE companies SET build_tags = '[]', domain_tags = '[]' WHERE id = 'ziroc';
