"""Build src/india-map.ts, the state outlines the "Where they are" widget draws.

The boundaries are DataMeet's States/Admin2 layer (https://github.com/datameet/maps,
CC BY 4.0), which follows the Survey of India map as revised in 2021: Jammu and Kashmir
and Ladakh as two union territories, each drawn to India's claimed boundary. A map on
this page that drew any other outline would be the first thing an Indian reader noticed.

Run from the repo root, with the five Admin2.* files in a directory of your choice:

    npx -y mapshaper@0.6 -i DIR/Admin2.shp \
      -proj '+proj=lcc +lat_1=12 +lat_2=28 +lat_0=22 +lon_0=82 +datum=WGS84' \
      -simplify 0.4% keep-shapes planar -clean -o format=geojson precision=10 DIR/states.json
    python3 scripts/india-map.py DIR/states.json > src/india-map.ts

Lambert conformal conic, so Kashmir is not stretched the way plain longitude and
latitude stretch it. 0.4% of the vertices is about 19 KB of path: a state is a place to
click, not a survey. Simplification is topological, so neighbours still share an edge.
"""

import json
import sys

WIDTH = 560

# The page's state names are the DPIIT register's; the layer's differ for two of them.
RENAME = {'Jammu & Kashmir': 'Jammu and Kashmir', 'Andaman & Nicobar': 'Andaman and Nicobar Islands'}


def rings(geometry):
    polygons = geometry['coordinates'] if geometry['type'] == 'MultiPolygon' else [geometry['coordinates']]
    for polygon in polygons:
        yield from polygon


def main(path):
    features = json.load(open(path))['features']
    xs = [x for f in features for r in rings(f['geometry']) for x, _ in r]
    ys = [y for f in features for r in rings(f['geometry']) for _, y in r]
    min_x, max_y = min(xs), max(ys)
    k = WIDTH / (max(xs) - min_x)
    height = round((max_y - min(ys)) * k)

    paths = {}
    for f in features:
        name = RENAME.get(f['properties']['ST_NM'], f['properties']['ST_NM'])
        d = []
        for ring in rings(f['geometry']):
            points = [(round((x - min_x) * k), round((max_y - y) * k)) for x, y in ring]
            kept = [points[0]]
            for p in points[1:]:
                if p != kept[-1]:
                    kept.append(p)
            if len(kept) < 4:
                # An island too small to draw at this size is still part of the map: a dot.
                cx = round(sum((x - min_x) * k for x, _ in ring) / len(ring))
                cy = round(sum((max_y - y) * k for _, y in ring) / len(ring))
                dot = f'M{cx - 1} {cy - 1}h3v3h-3z'
                if dot not in d:
                    d.append(dot)
                continue
            if kept[-1] == kept[0]:
                kept.pop()
            steps = []
            for (px, py), (x, y) in zip(kept, kept[1:]):
                steps.append(f'{x - px} {y - py}')
            d.append(f'M{kept[0][0]} {kept[0][1]}l' + ' '.join(steps).replace(' -', '-') + 'z')
        paths[name] = ''.join(d)

    print('// Generated by scripts/india-map.py from DataMeet States/Admin2 (CC BY 4.0). Do not edit.')
    print(f'export const INDIA_MAP_WIDTH = {WIDTH};')
    print(f'export const INDIA_MAP_HEIGHT = {height};')
    print('export const INDIA_STATES: Record<string, string> = {')
    for name in sorted(paths):
        print(f'\t{json.dumps(name)}: {json.dumps(paths[name])},')
    print('};')


if __name__ == '__main__':
    main(sys.argv[1])
